export const FETCH_SNIPPETS = "FETCH_SNIPPETS";
export const CREATE_SNIPPET = "CREATE_SNIPPET";
export const FETCH_SINGLE_SNIPPET = "FETCH_SINGLE_SNIPPET";
export const DELETE_SNIPPET = "DELETE_SNIPPET";
export const UPDATE_SNIPPET = "DELETE_SNIPPET";